# bootstrap VM with pre-Puppet tasks
---
- hosts: all
  become: no
  gather_facts: True
  vars:
    rpmbuild_topdir: '/home/vagrant/rpmbuild'
    shared_rpmbuild_topdir: '/vagrant/scratch/{{ ansible_distribution_major_version }}/rpmbuild'
    rpmbuild_dist: uga

  tasks:

    - name: install python-ssl for python 2.4 SSL validation
      yum:  name=python-ssl
      when: ansible_distribution_major_version == '5'
      become: yes

    - include: tasks/eupathdb-yumrepo.yml
      when: ansible_distribution_major_version > '5'
      become: yes

    - get_url: url=https://repos.fedorapeople.org/repos/pulp/pulp/rhel-pulp.repo
               dest=/etc/yum.repos.d/pulp-v2-stable.repo
      when: ansible_distribution_major_version > '5'
      become: yes

    - yum: name=epel-release
      become: yes

    - yum: name="{{ item }}"
      with_items:
        - bzip2-devel
        - cpanspec
        - db4-devel
        - gcc-c++
        - gdbm-devel
        - git
        - libpcap-devel
        - libcurl-devel
        - libpng-devel
        - libxml2-devel
        - ncurses-devel
        - openssl-devel
        - python-virtualenv
        - readline-devel
        - rpm-build
        - rpmdevtools
        - rubygem-gem2rpm
        - sqlite-devel
        - tk-devel
        - xz-devel
        - zlib-devel
      become: yes

    - yum: name="{{ item }}"
      with_items:
        - perl-ExtUtils-MakeMaker
        - perl-Test-Simple
        - pulp-admin-client
        - pulp-python-admin-extensions
        - pulp-rpm-admin-extensions
        - python-pip
        - redhat-lsb-core
      when: ansible_distribution_major_version > '5'
      become: yes

    - include: tasks/rpmbuild.yml
    - include: tasks/R2spec.yml

    - yum: name="{{ item }}"
      with_items:
        - python27-devel
      become: yes
      when: ansible_distribution_major_version == '6'

    - yum: name="{{ item }}"
      with_items:
        - python-devel
        - rpm-sign
      become: yes
      when: ansible_distribution_major_version == '7'

    - include: tasks/apidb-ca.yml
      when: ansible_distribution_major_version > '5'
    - include: tasks/apidb-ca-el5.yml
      when: ansible_distribution_major_version == '5'

    - name: check for existing dot files for vagrant user
      stat: path='{{ item.dest }}'
      register: dotfiles
      with_items:
        - { src: 'files/vagrant_bash_profile',
            dest: '.bash_profile'
          }
        - { src: 'files/vagrant_bash_logout',
            dest: '.bash_logout'
          }
        - { src: 'files/vagrant_bash_history',
            dest: '.bash_history'
          }

    - name: install dot files for vagrant user
      copy: src='{{ item.item.src }}'
            dest='/home/vagrant/{{ item.item.dest }}'
            owner=vagrant
            mode=0644
      when: item.stat.exists == false
      with_items: '{{ dotfiles.results }}'

    - name: add git host to known_hosts
      known_hosts: path="/home/vagrant/.ssh/known_hosts"
                   host='git.apidb.org'
                   key="{{ lookup('pipe','ssh-keyscan git.apidb.org') }}"

    - file: path=/home/vagrant/bin
            state=directory
            owner=vagrant
    - template: dest=/home/vagrant/bin/upload-workflow-pkg
                src=templates/upload-workflow-pkg.j2
                owner=vagrant
                mode=755

    - copy: src=sensitive/gnupg/
            dest=/home/vagrant/.gnupg
            mode=0600
            force=yes
            directory_mode=0700

    - ini_file: dest=/etc/pulp/admin/admin.conf
                section=server
                option="{{ item.option }}"
                value="{{ item.value }}"
      when: ansible_distribution_major_version > '5'
      become: yes
      with_items:
        - { option: 'host',
            value: 'pulp.uga.apidb.org'
          }
        - { option: 'port',
            value: '443'
          }
        - { option: 'api_prefix',
            value: '/pulp/api',
          }

    - name: install Pulp pseudo-admin scripts for EL5
      copy: src='files/{{ item }}'
            dest='/home/vagrant/bin/{{ item }}'
            owner=vagrant
            mode=0755
      when: ansible_distribution_major_version == '5'
      with_items:
        - pulp-publish
        - pulp-upload
        - jq

