# bootstrap VM with pre-Puppet tasks
---
- hosts: all
  sudo: no
  gather_facts: True
  vars:
    rpmbuild_topdir: '/home/vagrant/rpmbuild'
    shared_rpmbuild_topdir: '/vagrant/scratch/{{ ansible_distribution_major_version }}/rpmbuild'
    rpmbuild_dist: uga

  tasks:

    - include: tasks/eupathdb-yumrepo.yml
      sudo: yes

    - get_url: url=https://repos.fedorapeople.org/repos/pulp/pulp/rhel-pulp.repo
               dest=/etc/yum.repos.d/pulp-v2-stable.repo
      sudo: yes

    - yum: name=epel-release
      sudo: yes

    - yum: name="{{ item }}"
      with_items:
        - git
        - gcc-c++
        - zlib-devel
        - bzip2-devel
        - openssl-devel
        - libpng-devel
        - ncurses-devel
        - sqlite-devel
        - readline-devel
        - tk-devel
        - gdbm-devel
        - db4-devel
        - libpcap-devel
        - xz-devel
        - rpm-build
        - rpmdevtools
        - pulp-admin-client
        - pulp-rpm-admin-extensions
        - pulp-python-admin-extensions
        - rubygem-gem2rpm
        - python-virtualenv
        - python-pip
        - cpanspec
        - perl-ExtUtils-MakeMaker
        - perl-Test-Simple
      sudo: yes

    - include: tasks/rpmbuild.yml

    - yum: name="{{ item }}"
      with_items:
        - python27-devel
      sudo: yes
      when: ansible_distribution_major_version == '6'

    - yum: name="{{ item }}"
      with_items:
        - python-devel
        - rpm-sign
      sudo: yes
      when: ansible_distribution_major_version == '7'

    - include: tasks/apidb-ca.yml

    - name: install vagrant dot files
      copy: src='{{ item.src }}'
            dest='/home/vagrant/{{ item.dest }}'
            owner=vagrant
            mode=0644
      with_items:
        - { src: 'files/vagrant_bash_profile',
            dest: '.bash_profile'
          }
        - { src: 'files/vagrant_bash_logout',
            dest: '.bash_logout'
          }

    - name: add git host to known_hosts
      known_hosts: path="/home/vagrant/.ssh/known_hosts"
                   host='git.apidb.org'
                   key="{{ lookup('pipe','ssh-keyscan git.apidb.org') }}"

    - file: path=/home/vagrant/bin
            state=directory
            owner=vagrant
    - template: dest=/home/vagrant/bin/upload-workflow-pkg
                src=templates/upload-workflow-pkg.j2
                owner=vagrant
                mode=755

    - copy: src=sensitive/gnupg/
            dest=/home/vagrant/.gnupg
            mode=0600
            force=yes
            directory_mode=0700

    - ini_file: dest=/etc/pulp/admin/admin.conf
                section=server
                option="{{ item.option }}"
                value="{{ item.value }}"
      sudo: yes
      with_items:
        - { option: 'host',
            value: 'pulp.uga.apidb.org'
          }
        - { option: 'port',
            value: '443'
          }
        - { option: 'api_prefix',
            value: '/pulp/api',
          }
