# bootstrap VM with pre-Puppet tasks
---
- hosts: all
  sudo: no
  gather_facts: True
  vars:
    rpmbuild_topdir: /vagrant/scratch/rpmbuild
    rpmbuild_dist: uga

  tasks:

    - include: tasks/eupathdb-yumrepo.yml
      sudo: yes

    - get_url: url=https://repos.fedorapeople.org/repos/pulp/pulp/rhel-pulp.repo
               dest=/etc/yum.repos.d/pulp-v2-stable.repo
      sudo: yes

    - yum: name=https://dl.fedoraproject.org/pub/epel/6/x86_64/epel-release-6-8.noarch.rpm
      sudo: yes

    - yum: name="{{ item }}"
      with_items:
        - git
        - rpm-build
        - rpmdevtools
        - pulp-admin-client
        - pulp-rpm-admin-extensions
        - rubygem-gem2rpm
        - python-virtualenv
        - python-pip
        - python27-devel
      sudo: yes

    - include: tasks/apidb-ca.yml

    - name: add git host to known_hosts
      known_hosts: path="/home/vagrant/.ssh/known_hosts"
                   host='git.apidb.org'
                   key="{{ lookup('pipe','ssh-keyscan git.apidb.org') }}"

    - template: dest=/home/vagrant/.rpmmacros
                src=templates/rpmmacros.j2

    - file: path="{{ rpmbuild_topdir }}/{{ item }}"
            state=directory
      with_items:
        - BUILD
        - BUILDROOT
        - RPMS
        - SOURCES
        - SPECS
        - SRPMS

    - copy: src=sensitive/gnupg/
            dest=/home/vagrant/.gnupg

    - file: path=/home/vagrant/rpmbuild
            src="{{rpmbuild_topdir}}"
            state=link

    - copy: src=files/macros.eupathdbworkflow
            dest=/etc/rpm/macros.eupathdbworkflow
            owner=root
            group=root
            mode=-644
      sudo: yes

    - ini_file: dest=/etc/pulp/admin/admin.conf
                section=server
                option="{{ item.option }}"
                value="{{ item.value }}"
      sudo: yes
      with_items:
        - { option: 'host',
            value: 'pulp.uga.apidb.org'
          }
        - { option: 'port',
            value: '443'
          }
        - { option: 'api_prefix',
            value: '/pulp/api',
          }
