
- yum: name=ca-certificates
  sudo: yes

- command: "/usr/bin/update-ca-trust check 2>&1"
  register: ca_trust_enabled
  changed_when: false
  sudo: no

- shell: /usr/bin/update-ca-trust enable
  when: ca_trust_enabled.stdout.find('DISABLED') != -1
  sudo: yes
  
- copy: src=files/apidb-ca-rsa.crt
        dest=/etc/pki/ca-trust/source/anchors/
  register: ca_crt
  sudo: yes

- command: /usr/bin/update-ca-trust
  when: ca_crt.changed
  sudo: yes