# update-ca-trust in EL7 does not support check, enable commands, doesn't
# seem to require to be enabled.

- yum: name=ca-certificates
  sudo: yes

- command: "/usr/bin/update-ca-trust check 2>&1"
  register: ca_trust_enabled
  changed_when: False
  sudo: no
  when: ansible_distribution_major_version == '6'

- shell: /usr/bin/update-ca-trust enable
  sudo: yes
  when: ca_trust_enabled.stdout.find('DISABLED') != -1 and ansible_distribution_major_version == '6'
  
- copy: src=files/apidb-ca-rsa.crt
        dest=/etc/pki/ca-trust/source/anchors/
  register: ca_crt
  sudo: yes

- command: /usr/bin/update-ca-trust
  when: ca_crt.changed
  sudo: yes
