# Add EuPathDB YUM repos.
# CentOS 5 YUM requires python-hashlib to handle sha256-signed YUM repo
# data (avoiding "Error performing checksum")

- name: install python-hashlib for sha256 YUM checksums
  yum: name="{{ item }}"
  with_items:
    - python-hashlib
  when: ansible_distribution_major_version == '5'

- copy: src=files/RPM-GPG-KEY-EUPATHDB
        dest=/etc/pki/rpm-gpg/RPM-GPG-KEY-EUPATHDB
  register: gpgkeyeupathdb

- command: rpm --import /etc/pki/rpm-gpg/RPM-GPG-KEY-EUPATHDB
  when: gpgkeyeupathdb.changed

- template: src='{{ item.src }}'
            dest='{{ item.dest }}'
            force=yes
  with_items: 
    - { src: templates/eupathdb.repo.j2,
        dest: /etc/yum.repos.d/eupathdb.repo }
    - { src: templates/eupathdb-fasttrack.repo.j2,
        dest: /etc/yum.repos.d/eupathdb-fasttrack.repo }
    - { src: templates/eupathdb-workflow.repo.j2,
        dest: /etc/yum.repos.d/eupathdb-workflow.repo }
