# update-ca-trust in EL7 does not support check, enable commands, doesn't
# seem to require to be enabled.
# ca-certificates is not packaged for EL5.

- name: install ca-certificates package
  yum:
    name: ca-certificates
  become: yes

- name: update-ca-trust check
  command: "/usr/bin/update-ca-trust check 2>&1"
  register: ca_trust_enabled
  changed_when: False
  become: no
  when: ansible_distribution_major_version == '6'

- name: update-ca-trust enable
  shell: /usr/bin/update-ca-trust enable
  become: yes
  when: ansible_distribution_major_version == '6' and ca_trust_enabled.stdout.find('DISABLED') != -1
  
- name: install apidb-ca-rsa.crt
  copy:
    src: files/apidb-ca-rsa.crt
    dest: '{{ item }}'
  register: ca_crt
  become: yes
  with_items:
    - /etc/pki/ca-trust/source/anchors
    - /etc/pki/tls/certs

- name: update CA trust
  command: /usr/bin/update-ca-trust
  when: ca_crt.changed
  become: yes
