# Configure YUM repo for Pulp
# https://pulpproject.org

- name: Add Pulp YUM repo
  get_url:
    url: https://repos.fedorapeople.org/repos/pulp/pulp/rhel-pulp.repo
    dest: /etc/yum.repos.d/pulp-v2-stable.repo
  when: ansible_distribution_major_version > '6'
  become: yes
  register: pulpgpgkey

- name: import RPM-GPG-KEY-pulp-2
  rpm_key:
    state: present
    key: https://repos.fedorapeople.org/repos/pulp/pulp/GPG-RPM-KEY-pulp-2

  # EL6 support (incl. pulp-admin pkg) maxes out at Pulp 2.11
- name: Add Pulp YUM repo for EL6
  get_url:
    url: https://repos.fedorapeople.org/repos/pulp/pulp/rhel6-pulp.repo
    dest: /etc/yum.repos.d/rhel6-pulp.repo
  when: ansible_distribution_major_version == '6'
  become: yes