---
- hosts: all
  become: no
  gather_facts: True
  vars:
    rpmbuild_topdir: '/home/vagrant/rpmbuild'
    shared_rpmbuild_topdir: '/vagrant/scratch/{{ ansible_distribution_major_version }}/rpmbuild'
    rpmbuild_dist: uga

  tasks:

    - name: check for gpg signing keys on local Ansible host
      local_action: stat path=sensitive/gnupg
      register: stat_gpg_present

    - fail:
        msg: Directory `sensitive/gnupg` not found. See README.md for instructions.
      when: stat_gpg_present.stat.exists == False

    - name: install python-ssl for python 2.4 SSL validation for EL5
      yum:
        name: python-ssl
      when: ansible_distribution_major_version == '5'
      become: yes

    - name: Add EuPathDB YUM repo (skip if EL5)
      import_tasks: tasks/eupathdb-yumrepo.yml
      when: ansible_distribution_major_version > '5'
      become: yes

    - name: Add Pulp YUM repo (skip if EL5)
      import_tasks: tasks/pulp-yumrepo.yml
      when: ansible_distribution_major_version > '5'
      become: yes

    - name: Add EPEL YUM repo (skip if EL5)
      import_tasks: tasks/epel-yumrepo.yml
      when: ansible_distribution_major_version > '5'
      become: yes

    - name: yum clean all
      shell: yum clean all
      become: yes

    - name: install devel packages
      yum: 
        name: "{{ item }}"
      with_items:
        - bzip2-devel
        - cpanspec
        - db4-devel
        - facter
        - gcc-c++
        - gdbm-devel
        - git
        - libpcap-devel
        - libcurl-devel
        - libpng-devel
        - libxml2-devel
        - ncurses-devel
        - openssl-devel
        - python-virtualenv
        - R-Rcpp-devel
        - readline-devel
        - rpm-build
        - rpmdevtools
        - rubygem-gem2rpm
        - sqlite-devel
        - tk-devel
        - xz-devel
        - zlib-devel
      become: yes

    - name: install Pulp client packages
      yum:
        name: "{{ item }}"
      with_items:
        - perl-ExtUtils-MakeMaker
        - perl-Test-Simple
        - pulp-admin-client
        - pulp-python-admin-extensions
        - pulp-rpm-admin-extensions
        - python-pip
        - redhat-lsb-core
      when: ansible_distribution_major_version > '5'
      become: yes

    - import_tasks: tasks/rpmbuild.yml
    - import_tasks: tasks/R2spec.yml

    - name: install python27 devel packages for EL6
      yum:
        name: "{{ item }}"
      with_items:
        - python27-devel
      become: yes
      when: ansible_distribution_major_version == '6'

    - name: install python devel packages for EL7
      yum:
        name: "{{ item }}"
      with_items:
        - python-devel
        - rpm-sign
      become: yes
      when: ansible_distribution_major_version == '7'

    - import_tasks: tasks/apidb-ca.yml
      when: ansible_distribution_major_version > '5'
    - import_tasks: tasks/apidb-ca-el5.yml
      when: ansible_distribution_major_version == '5'

    - name: install persistent bash_history file
      template:
        dest: /home/vagrant/.bash_history_persistent
        src: templates/vagrant_bash_history.j2
        owner: vagrant
        mode: '0644'

    - name: install dot files for vagrant user
      copy:
        src: '{{ item.src }}'
        dest: '/home/vagrant/{{ item.dest }}'
        owner: vagrant
        mode: '0644'
      with_items:
        - { src: 'files/vagrant_bash_profile',
            dest: '.bash_profile'
          }
        - { src: 'files/vagrant_bash_logout',
            dest: '.bash_logout'
          }

    - name: add git host to known_hosts
      known_hosts:
        path: "/home/vagrant/.ssh/known_hosts"
        host: 'git.apidb.org'
        key: "{{ lookup('pipe','ssh-keyscan -p 2112 git.apidb.org') }}"

    - name: mkdir /home/vagrant/bin
      file:
        path: /home/vagrant/bin
        state: directory
        owner: vagrant
    - name: install upload-workflow-pkg script
      template:
        dest: /home/vagrant/bin/upload-workflow-pkg
        src: templates/upload-workflow-pkg.j2
        owner: vagrant
        mode: '0755'

    - name: install gnupg keys
      copy:
        src: sensitive/gnupg/
        dest: /home/vagrant/.gnupg
        mode: '0600'
        force: yes
        directory_mode: '0700'

    - name: configure Pulp admin
      ini_file:
        dest: /etc/pulp/admin/admin.conf
        section: server
        option: "{{ item.option }}"
        value: "{{ item.value }}"
      when: ansible_distribution_major_version > '5'
      become: yes
      with_items:
        - { option: 'host',
            value: 'pulp.uga.apidb.org'
          }
        - { option: 'port',
            value: '443'
          }
        - { option: 'api_prefix',
            value: '/pulp/api',
          }

    - name: install Pulp pseudo-admin scripts for EL5
      copy:
        src: 'files/{{ item }}'
        dest: '/home/vagrant/bin/{{ item }}'
        owner: vagrant
        mode: '0755'
      when: ansible_distribution_major_version == '5'
      with_items:
        - pulp-publish
        - pulp-upload
        - jq

